name: Build Application
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/app-workflow.yaml'
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/app-workflow.yaml'
jobs:
  build:
    steps:
      - checkout
      - run: mvn clean package
      - run: echo "BUILD OK"
  test:
    steps:
      - checkout
      - run: mvn test
      - run: echo "TEST OK"